### ISSUE TITLE
Speaker support (Audio) / 扬声器支持（音频）

### ISSUE THREAD

**Issue by kubawolanin** [louisZL/lumi-gateway-local-api#8]
It would be great if we had ability to control Gateway's speaker. I'm interested in features like playing local audio file and controlling volume.

如果我们有能力控制Gateway的扬声器，这将是巨大的。我有兴趣的功能，如播放本地音频文件，控制音量。

**Comment by aluminiumgeek** [comment]
Totally agree.

**Comment by aluminiumgeek** [comment]
Actually, latest update brings ringtone playing command (including user defined via Mihome app). I'm going to test it shortly
https://github.com/louisZL/lumi-gateway-local-api/blob/master/%E7%BD%91%E5%85%B3.md

**Comment by aluminiumgeek** [comment]
Nah, that probably requires firmware update which is not ready yet. I don't receive any answer from the gateway after this command.

**Comment by jon1012** [comment]
Is there any way to set the volume for this ? It is always very low

**Comment by aluminiumgeek** [comment]
Great. The command works after latest firmware upgrade (1.4.1_145.0141)

Not sure how to adjust volume. Changing it from the app doesn't seem to work.

**Comment by deennoo** [comment]
Add

/"vol":xx to your command.

You can have exemple here : https://github.com/lunarok/jeedom_xiaomihome

**Comment by aluminiumgeek** [comment]
Thanks, @deennoo, it works!

Where did you find additional docs for this?

**Comment by deennoo** [comment]
On source i give, looks like dev got answer from Xiaomi dev team.

Source give élément to drive mi Hoover robot and other wifi device.

**Comment by bastshoes** [comment]
Hello. What is valid mid. GW is playing always default alarm rigtone

**Comment by aluminiumgeek** [comment]
@bastshoes everything as described in docs works for me. Make sure you pass `mid` as integer, not string.

**Comment by bastshoes** [comment]
@aluminiumgeek Thank! Problem was in mid type. 
Спасибо!

**Comment by kubawolanin** [comment]
Closing since it's already implemented:
https://github.com/louisZL/lumi-gateway-local-api/blob/master/%E7%BD%91%E5%85%B3.md
